//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DwarfFortressModMerger {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DwarfFortressModMerger.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Dwarf Fortress Mod (Drag ZIP File Here).
        /// </summary>
        internal static string choose_ext_mod {
            get {
                return ResourceManager.GetString("choose_ext_mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Dwarf Fortress Vanilla (Drag ZIP File Here).
        /// </summary>
        internal static string choose_ext_van {
            get {
                return ResourceManager.GetString("choose_ext_van", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Output Directory (Drag Directory Here).
        /// </summary>
        internal static string choose_output_dir {
            get {
                return ResourceManager.GetString("choose_output_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear History.
        /// </summary>
        internal static string clear_hist {
            get {
                return ResourceManager.GetString("clear_hist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading mod zip file:.
        /// </summary>
        internal static string error_mod_zip {
            get {
                return ResourceManager.GetString("error_mod_zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading vanilla zip file:.
        /// </summary>
        internal static string error_van_zip {
            get {
                return ResourceManager.GetString("error_van_zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Extracting Mod ZIP File, Merging Directories.
        /// </summary>
        internal static string fin_exct_mod_zip {
            get {
                return ResourceManager.GetString("fin_exct_mod_zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Extracting Vanilla ZIP File, Starting Mod ZIP extraction.
        /// </summary>
        internal static string fin_exct_van_zip {
            get {
                return ResourceManager.GetString("fin_exct_van_zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished merging vanilla and mod zips, Making final changes.
        /// </summary>
        internal static string fin_merge {
            get {
                return ResourceManager.GetString("fin_merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep existing data/save directory.
        /// </summary>
        internal static string merge_exist_savedir {
            get {
                return ResourceManager.GetString("merge_exist_savedir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep existing data/init directory.
        /// </summary>
        internal static string merge_ext_initdir {
            get {
                return ResourceManager.GetString("merge_ext_initdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open directory on complete.
        /// </summary>
        internal static string open_dir_complete {
            get {
                return ResourceManager.GetString("open_dir_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string ready {
            get {
                return ResourceManager.GetString("ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run game on complete.
        /// </summary>
        internal static string run_game_complete {
            get {
                return ResourceManager.GetString("run_game_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting extraction of vanilla zip.
        /// </summary>
        internal static string start_exct_van_zip {
            get {
                return ResourceManager.GetString("start_exct_van_zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Merge.
        /// </summary>
        internal static string start_merge {
            get {
                return ResourceManager.GetString("start_merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
    }
}
